### ISSUE TITLE
:^)

### ISSUE THREAD

**Issue by ghost** [RoadKillCat/roadkillcat.github.io#1]
![image](https://user-images.githubusercontent.com/12225238/28057424-f4826a30-6617-11e7-88b5-c92a914621cd.png)

**Comment by ghost** [comment]
Improved css:

```css
html{
	background-color: #ff0081;
}
body {
	margin: 0;
	padding: 0;
	overflow: auto;
}

#banner {
	position: fixed;
	z-index: 1;
	top: 0;
	width: 100%;
	background-color: #ff66d7;
	max-width: none;
	height: 100px;
}

#logo {
	position: relative;
	display: block;
	padding: 5px;
	width: 80px;
	height: 80px;
	top: 5px;
	left: 5px;
	color: white;
	cursor: pointer;
}

#logo_txt {
	position: relative;
	text-align: center;
	font-family: courier;
	font-size: 14px;
	line-height: 20px;
}

#logo_img {
	display: block;
	margin: auto;
	width: 60px;
	height: 60px;
}

#menu {
	position: relative;
	display: inline-block;
	height: 40px;
	padding: 10px;
	bottom: 50px;
	left: 50%;
	margin-left: -131.5px;	 /*half of the menu div which doesn't change but does w/ font-size */
}

.nav_button {
	display: inline-block;
	/* background-color: #00B0E0; */
	height: 100%;
	text-align: center;
	line-height: 40px;
	color: white;
	font-family: comic sans MS;
	font-size: 20px;
	margin-top: -3px;
	padding: 3px;
	cursor: pointer;
}

#main {
	position: relative;
	margin-top: 100px;
	padding-top: 10px;
	width: 100%;
	background-image: url(http://www.publicdomainpictures.net/pictures/130000/velka/rainbow-background-1438899140wt8.jpg);
}

h1 {
	margin: 0;
	padding: 12px;
	text-align: center;
	font-size: 45px;
	font-family: comic sans MS;
}

#main_container {
	width: 60%;
	margin: 0 auto;
}

p {
	margin: 0;
	padding: 6px;
	font-size: 16px;
	font-family: comic sans MS;
}

#wispa_img {
	display: block;
	margin: 0 auto;
	width: 720;
}


#footer {
	bottom: 0;
	width: 100%;
	background-color: #ff66d7;
	padding-top: 4px;
	padding-bottom: 4px;
	text-align: center;
	font-size: 12px;
	font-family: comic sans MS;
}

/* div {border: 3px solid pink} */
```
